### ISSUE TITLE
Walletconnect success/fail receipt never reaches the client

### ISSUE THREAD

**Issue by souvikmishra** [blocknative/web3-onboard#2318]
### Current Behavior

Let us say I want to approve 1 usdc, I send a request to approve the token (from my dapp). The request reaches to safe wallet (which I use via walletconnect connection). Now after signing in safe wallet, the transaction gets mined, but that message never reaches the client from where I sent the approve request from i.e. the dapp.

### Expected Behavior

The fail/success reciept of the transaction should reach the dapp, so that the user journey can progress further.

### Steps To Reproduce

You connect your safe wallet to your dapp which is in sveltekit, via the wallet connect option and try to approve or do any other contract interaction.

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

^2.22.3

### Node Version

21.7.3

### What browsers are you seeing the problem on?

Firefox, Chrome

### Anything else?

Walletconnect module config
```
const walletConnect = walletConnectModule({
	projectId: import.meta.env.VITE_PROJECT_ID,
	requiredChains: valid_chain_ids,
	dappUrl: environment.dapp_url
});
```

we use ethers ^6.13.3, and use `txn.wait()` to wait for the txn reciept

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by souvikmishra** [comment]
bump

**Comment by Adamj1232** [comment]
@souvikmishra we have updated the `@web3-onboard/walletconnect` package with the latest version of the WC deps. Please upgrade and try again as the pinned WC deps to the previous version have been causing other issues which are now fixed

**Comment by souvikmishra** [comment]
Hey! Tried with the latest version of `@web3-onboard/walletconnect` the issue still persists

**Comment by Adamj1232** [comment]
@souvikmishra hmmmm I am unable to reproduce - can you provide me with reproducible code?

**Comment by souvikmishra** [comment]
bump
